### ISSUE TITLE
Work inside new browsers after death of silverlight

### ISSUE THREAD

**Issue by mahdiit** [jariq/Pkcs11Interop#16]
hi
it seems that new browsers will discontinue supporting Silverlight 
like chrome, Firefox and new Microsoft browser (Edge browser)
according to reports in here: http://superuser.com/questions/748306/what-does-the-removal-of-npapi-plugin-support-mean-to-an-end-user

but we have an application that use this library through Silverlight,
how we can do? for support our project after death of Silverlight?
it there any new way?

will Microsoft support these browsers? 

because Microsoft will not support Silverlight
Microsoft explain here (Compatible Operating Systems and Browsers): http://www.microsoft.com/getsilverlight/Get-Started/Install/Default.aspx

** Chrome is supported up to version 41. For support on Chrome 42 and later, see KB3058254.
*** Silverlight is not available in the Microsoft Edge browser, but is supported in Internet Explorer.

**Comment by jariq** [comment]
Hello Mahdi,

Pkcs11Interop.Silverlight requires Silverlight 5 and it currently works in Internet Explorer and Mozilla Firefox browsers on all supported versions of Microsoft Windows operating system. It does not work on Mac OS X because it requires "elevated trust" and "platform invoke" features which are supported only on Windows platform [0].

You however seems to be more concerned about the future of Silverlight as a technology itself and the list of the browsers supported by it. Microsoft has previously stated that Silverlight 5 will be supported from 12/9/2011 to 10/12/2021 [1]. Silverlight 5 currently works in Internet Explorer on Windows, Safari on OSX and Mozilla Firefox on both platforms [2]. It previously worked also in Chrome browser but Google recently dropped support for NPAPI plugins [3][4] which affected (made unusable) not only Silverlight but also JAVA and other technologies.

I am not aware of any currently available "cross browser" technology for the development of browser plugins that would support all three mentioned browsers. It seems rather common these days to develop separate solutions [5][6] for each browser i.e. ActiveX component for Internet Explorer, NPAPI plugin for Mozilla Firefox and application utilizing Native Messaging for Google Chrome. Microsoft Edge may still be considered "UNKNOWN". There is also a FireBreath project trying to fix this mess [7] but version 2.0 still seems to be in early development stages.

Hope this helps.

Regards, Jaroslav

[0] https://github.com/jariq/Pkcs11Interop/issues/14
[1] https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Microsoft%20Silverlight%205&Filter=FilterNO
[2] http://www.microsoft.com/getsilverlight
[3] http://blog.chromium.org/2013/09/saying-goodbye-to-our-old-friend-npapi.html
[4] http://www.chromium.org/developers/npapi-deprecation
[5] https://github.com/open-eid/browser-token-signing
[6] https://github.com/open-eid/chrome-token-signing
[7] http://www.firebreath.org/display/documentation/FireBreath+2.0%3A+Browser+Plugins+in+a+post-NPAPI+world

**Comment by mahdiit** [comment]
thanks for guide i read articles and think about future, it is hard to deiced what happen to new modern browsers plugin development because seems that they are in war 

i think i must wait and see what happen , but think about a new way (a way that i must invent!) for using it in my project
