### ISSUE TITLE
Create X509 Public key certificate from generated key pair

### ISSUE THREAD

**Issue by lkn2993** [jariq/Pkcs11Interop#19]
Hi.
Ive recently started programming with pkcs11interop, the features and examples of this application Is amazing but I cant find an example regarding the subject, which is really necessary for generating a valid ms_word (openxml dsig)signature,
any help on this topic is appreciated. Thanks in advance

**Comment by jariq** [comment]
Hello, it is not possible to generate X.509 certificate with a PKCS#11 library alone - you need to use an additional general purpose cryptographic library such as for example [BouncyCastle](http://www.bouncycastle.org/csharp/). AFAIK there is no complete sample for certificate generation available but there is a [sample for a PKCS#10 certfication request generation](https://github.com/jariq/Pkcs11Interop.PkiUtils/blob/master/src/Pkcs11Interop.PkiUtils/CertificateRequest.cs#L96) which might be helpful for you because it demonstrates the intergration of Pkcs11Interop and BouncyCastle libraries.

**Comment by lkn2993** [comment]
but I'm a little confused
how can bouncy castle integrate with this library, even a little explanation is good.
and the example is incomplete, it doesn't generate any valid certificate :)

**Comment by lkn2993** [comment]
let me explain this a little bit.
the bouncycastle example for signing and generating an X509Ver3 certificate is found here:
http://stackoverflow.com/questions/7230330/sign-csr-using-bouncy-castle

Its just the fact that I can't figure out a way to implement this using the pkcs11interop lib.
Thanks for response btw

**Comment by jariq** [comment]
> how can bouncy castle integrate with this library, even a little explanation is good.

Have you examined the code of [Pkcs11Interop.PkiUtils](https://github.com/jariq/Pkcs11Interop.PkiUtils/) project I was linking in my previous comment?

**Comment by lkn2993** [comment]
It says "create" not import :)
Everyone knows how to import certificate, but... nobody knows how to create one?

**Comment by lkn2993** [comment]
that's fine I will find another way :)
