### ISSUE TITLE
Export Certificate id and data

### ISSUE THREAD

**Issue by lkn2993** [jariq/Pkcs11Interop#21]
Hello.
I was working with your library for a while but it seems that the library is actually not able to export certificates. In this example:

		            private static Dictionary<string, X509Certificate2> Certificates = new Dictionary<string, X509Certificate2>();
                    List<ObjectAttribute> template = new List<ObjectAttribute>();
					template.Add(new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_CERTIFICATE));
					template.Add(new ObjectAttribute(CKA.CKA_CERTIFICATE_TYPE, CKC.CKC_X_509));
					List<ObjectHandle> oObjCollection = session.FindAllObjects(template);

					foreach (var item in oObjCollection)
					{
						var oAttriVal = session.GetAttributeValue(item, new List<CKA>() {CKA.CKA_VALUE}).FirstOrDefault();
						var oAttriKey = session.GetAttributeValue(item, new List<CKA>() {CKA.CKA_ID}).FirstOrDefault();
                        Certificates[oAttriKey.GetValueAsString()] = new X509Certificate2(oAttriVal.GetValueAsByteArray());
                    }

I remember that the Ncryptoki actually used to return certificates as byte array so I could convert them to X509Certificate just by parsing them, but In this case, both oAttriVal and oAttriKey return null, so I'm not able to directly read the certificate and its ID(to retrieve the private key handle with the same ID that is).
But again, this might be an error in my template. :) 
So correct me if I'm wrong.

**Comment by jariq** [comment]
I don't see any obvious error in your code other than that you are trying to read the value of binary CKA_ID attribute into the string. Please [use pkcs11-logger to capture all unmanaged PKCS#11 calls made by your application](https://www.jimrich.sk/2015/12/15/troubleshooting-pkcs11interop-with-pkcs11-logger/) and share the logs with me if you want me to provide more detailed answer.

**Comment by jariq** [comment]
Any update on this issue? Will you be able to provide me with the logs?

**Comment by lkn2993** [comment]
I'm sorry but the project was suspended due to HSM hardware issue until today.
Ill restart my work today and report back the progress in 48 hours.
Thanks for your patience and compassion about this issue.

**Comment by lkn2993** [comment]
I know this sounds a little irrelevant, but how does the GetAttributeValue works exactly, for example I want to export modulus from a public key so what should I do about it?

**Comment by jariq** [comment]
First you need to find/create/generate object in order to get its `ObjectHandle` and after that read its attributes i.e. `CKA_MODULUS` with `Session::GetAttributeValue` method. Each attribute has its own data type defined in PKCS#11 specification so you need to read its value with an appropriate `ObjectAttribute::GetValueAs*` method. In case of `CKA_MODULUS` you need to use `ObjectAttribute::GetValueAsByteArray` because it is binary attribute.

Working code sample is available as [GetAttributeValueTest](https://github.com/jariq/Pkcs11Interop/blob/3.0.0/src/Pkcs11InteropTests/HighLevelAPI/_16_GetAndSetAttributeValueTest.cs#L33) and more information on this topic can be found in Chapter 10 of [PKCS#11 v2.20 specification](https://github.com/jariq/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf).

**Comment by lkn2993** [comment]
Done and done,
The problem seems to be non existent in version 2 of your library, the null value is only returned in version 3, could be a problem with dll.

The final code is:

    List<CKA> pubKeyAttrsToRead = new List<CKA>();
    pubKeyAttrsToRead.Add(CKA.CKA_LABEL);
    pubKeyAttrsToRead.Add(CKA.CKA_ID);

    List<ObjectAttribute> pubKeyAttributes =
    CurrentSession.GetAttributeValue(pubKeyObjectHandle, pubKeyAttrsToRead);

Which worked properly.

However that's not top priority issue now. :)

**Comment by jariq** [comment]
Pkcs11Interop v3 is superior to Pkcs11Interop v2 in many ways and should be preferred for all applications not only because it contains many improvements but because it also fixes a lot of issues. You are stating that the same code which works with v2 does not work with v3. If this is true then you may have found a bug which was not caught by our automated tests. I would be grateful if you could [use pkcs11-logger to capture all unmanaged PKCS#11 calls made by your application](https://www.jimrich.sk/2015/12/15/troubleshooting-pkcs11interop-with-pkcs11-logger/) using Pkcs11Interop v2 and then v3 and share the logs with me so I can analyze the real cause of the problem. It should take you only a few minutes of your time and it could help me make the library (or your code) better.

**Comment by lkn2993** [comment]
I'm sorry but that simply cannot be done, the error which is returned by the application is simply beyond the pkcs11 logger responsibility(it happens in .net code)
The error is(Unmanaged error, value cannot be null) which is silently bypassed if our pkcs11 dll is in release mode(but catches it in debug mode).
Do you still need more information regarding this issue? As I said its very likely that the problem is in our side.

**Comment by jariq** [comment]
OK then. Let's agree that problem is on your side :relaxed:. Feel free to reopen this issue if you change your mind.
